### ISSUE TITLE
ReactNodeArray is not defined

### ISSUE THREAD

**Issue by JodiRaina** [VolkenoMakers/react-native-drag-drop#1]
Error ReactNodeArray is not defined if in dropzone have more than one children, how to solve that?
![WhatsApp Image 2021-06-09 at 10 40 12](https://user-images.githubusercontent.com/50507587/121289455-2c4f0280-c90f-11eb-9b92-7a7668ee81bb.jpeg)

**Comment by babacarMbengue12** [comment]
corrected on version 1.0.7
