### ISSUE TITLE
[feat] how can i change core to set 2 column in one zone with props || one-way movement A -> B and B cant return to A

### ISSUE THREAD

**Issue by MinhOmega** [VolkenoMakers/react-native-drag-drop#2]
Hi authors,
I have 2 points and after research in docs and diving deep into code still wondering:
 - How can I change core to set 2 columns in one zone with props 
 Such as that image: 
![CleanShot 2022-04-15 at 01 26 54@2x](https://user-images.githubusercontent.com/49482201/163453896-a4cc9b86-c36c-4728-9378-b2b20f8fb4b8.png)

 - How can make one-way movement A -> B and B cant return to A
  In lib, I see we can move back and forth between columns, but have any idea for make on-way and we will disable return back to old column?
 Thanks for reading and hope ur guys can response ASAP

**Comment by trung1051996** [comment]
Hi MinhOmega,
Its nice for UI.

**Comment by HoaiPhuoc97** [comment]
I also have the same situation, expect an urgent solution. Thanks

**Comment by babacarMbengue12** [comment]
Hello @MinhOmega @HoaiPhuoc97 
its possible now to give as parameter the number of columns. 
please check the last version of the [package](https://www.npmjs.com/package/volkeno-react-native-drag-drop) section **Usage with multiple collumns**

**Comment by MinhOmega** [comment]
Many thanks, @babacarMbengue12 , i check and will create PR for this feature, update and fix some bugs and spelling mistakes.
