### ISSUE TITLE
[feat] Need one option to re-render zones data when save zones into state such as enableReinitialize in Formik.

### ISSUE THREAD

**Issue by MinhOmega** [VolkenoMakers/react-native-drag-drop#3]
Hi authors,
As title, i intergate your lib but have some problem with call API when change between 2 columns, so if posible can you help to provide a props to handle re-render **zones component** when props `zones` had change. Because i try to dive deep in code and can not do it.
- Video demo process:
https://cln.sh/ZeKUxl
- Link github of Formik so your guys can check the example i think helpfully:
https://github1s.com/jaredpalmer/formik/blob/HEAD/packages/formik/src/Formik.tsx.
If not clear pls contact me via email vnqminh0502@gmail.com.
Thanks for help here and hope get your reply as soon as posible.

**Comment by babacarMbengue12** [comment]
Hello @MinhOmega,
I have added the requested feature you can watch this [demo video](https://drive.google.com/file/d/15MJ9CRckYzVUVTZ7e6DJsVC6nLZX_fiA/view?usp=sharing)

**Comment by MinhOmega** [comment]
Hi @babacarMbengue12 ,
It worked for me, many thanks for support here 🥰
